import React from 'react';
import {FlatList, RefreshControl, StyleSheet, Text, View} from 'react-native';
import type {BottomTabScreenProps} from '@react-navigation/bottom-tabs';
import type {CompositeScreenProps} from '@react-navigation/native';
import type {NativeStackScreenProps} from '@react-navigation/native-stack';
import {BannerCarousel, CategoryCard, ProductCard, SearchBar} from '@/components/molecules';
import {AppHeader, EmptyState, ErrorState, MainTemplate, Section} from '@/components/organisms';
import {DeliveryTimer, Skeleton} from '@/components/atoms';
import {colors, spacing} from '@/constants';
import {useGetBootstrapQuery} from '@/services/blinkitApi';
import type {MainStackParamList, MainTabParamList} from '@/types/navigation';

type Props = CompositeScreenProps<BottomTabScreenProps<MainTabParamList, 'Home'>, NativeStackScreenProps<MainStackParamList>>;
export const HomeScreen = ({navigation}: Props) => { const {data, isLoading, isError, refetch, isFetching} = useGetBootstrapQuery(); if (isLoading) return <MainTemplate><Skeleton height={56} /><Skeleton height={140} /><Skeleton height={220} /></MainTemplate>; if (isError || !data) return <MainTemplate><ErrorState message="Could not load the store." /></MainTemplate>; return <MainTemplate><AppHeader title="Delivery in 10 minutes" subtitle="A-1402, Sunrise Apartments, Indiranagar" /><SearchBar value="" onChangeText={() => navigation.navigate('Search')} /><View style={styles.space}><DeliveryTimer minutes={10} /></View><FlatList horizontal data={data.categories} keyExtractor={i => i.id} showsHorizontalScrollIndicator={false} renderItem={({item}) => <View style={styles.catPill}><Text style={styles.catIcon}>{item.icon}</Text><Text style={styles.catLabel}>{item.title.split(' ')[0]}</Text></View>} refreshControl={<RefreshControl refreshing={isFetching} onRefresh={refetch} />} /><Section title="Top Offers" action="See all"><BannerCarousel /></Section><Section title="Best Sellers" action="See all"><FlatList horizontal data={data.products.slice(0, 12)} keyExtractor={i => i.id} showsHorizontalScrollIndicator={false} renderItem={({item}) => <ProductCard product={item} onPress={() => navigation.navigate('ProductDetail', {productId: item.id})} />} /></Section><Section title="Shop by category"><View style={styles.grid}>{data.categories.map(c => <CategoryCard key={c.id} category={c} onPress={() => navigation.navigate('ProductListing', {categoryId: c.id})} />)}</View></Section><Section title="Deal of the Day"><ProductCard compact product={data.products[14] ?? data.products[0]} onPress={() => navigation.navigate('ProductDetail', {productId: (data.products[14] ?? data.products[0]).id})} /></Section>{data.products.length === 0 ? <EmptyState title="No products" body="Please pull to refresh." /> : null}</MainTemplate>; };
const styles = StyleSheet.create({space: {marginVertical: spacing.md}, catPill: {width: 82, alignItems: 'center', marginRight: spacing.sm, padding: spacing.xs, backgroundColor: colors.backgroundMuted, borderRadius: 16}, catIcon: {fontSize: 25}, catLabel: {fontWeight: '800', fontSize: 12, color: colors.textPrimary}, grid: {flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'space-between'}});
